// fancy-ui-vue — public barrel. One export block per component folder,
// mirroring the Svelte and React barrels. The cameleon skin engine is
// deliberately NOT here (parity with the other two barrels); it ships through
// the "fancy-ui-vue/cameleon" subpath export instead.
// GENERATED between migration waves — do not edit per-component by hand.
export { cn } from "./utils.js";

// The Svelte/React barrels' non-component lines, minus the registry block
// (the docs site's own tooling, not ported).
export * from "./sound/index.js";
export type * from "./internals/ai-types.js";
export type * from "./internals/motion/types.js";

// Components (alphabetical; regenerated by the registrar between waves).
export * from "./components/dialog/index.js";
export * from "./components/presence/index.js";
export * from "./components/select/index.js";
